### ISSUE TITLE
Specific SVG path data not processed correctly

### ISSUE THREAD

**Issue by tabrms** [praeclarum/NGraphics#103]
Hi,
following SVG was not processed correctly

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 160 160">
	<path d="M152.042,146.481c3.63,0,5.7-4.131,4.148-7.229L84.114,15.324a4.865,4.865,0,0,0-8.3,0L3.742,139.25c-2.074,3.1.519,7.229,4.148,7.229Z" fill="#990000"/>
</svg>

```

Expected behavior is to draw something like this
![image](https://user-images.githubusercontent.com/3337580/54884920-d9e0b300-4e76-11e9-97a9-0cc35d0f3df9.png)

Tested on Xamarin Forms 4.0 Android project on NGraphics 1.6.0-beta1
Processed directly on device - Samsung Tab 2 Active on API 27 (Android 8.1)

**Comment by tabrms** [comment]
As an addition - another example. Just adding in case you'll be able to trace the issue.
`
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 160 160"><path d="M26.56,80,80,26.56,133.44,80l-9.69,9.37L86.56,52.19v81.25H73.44V52.19L35.94,89.38Z"/></svg>
`

**What was drawn**
![image](https://user-images.githubusercontent.com/3337580/54885300-e6670a80-4e7a-11e9-8a5b-b34929b0e290.png)



**What was expected**
![image](https://user-images.githubusercontent.com/3337580/54885248-4f9a4e00-4e7a-11e9-94dd-c3094dedba10.png)

**Comment by tabrms** [comment]
In case it will help somehow - I've changed a path data to following and NGraphics processed it correctly

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 160 160"><path d="M26.56,80L80,26.56L133.44,80l-9.69,9.38L86.56,52.19v81.25H73.44V52.19l-37.5,37.19L26.56,80z"/></svg>`


Anyway, just to make it clear - all browsers and vector graphics apps processed any following samples correctly.

**Comment by praeclarum** [comment]
Hello! Sorry for the long delay but I fixed this today. The problem lied in the parsing of numbers with negative signs with spaces. Thank you for the detailed descriptions!
