### ISSUE TITLE
Is it possible to draw on a Windows.UI.Xaml.Controls.Canvas?

### ISSUE THREAD

**Issue by tlycken** [praeclarum/NGraphics#19]
I'm trying to figure out how best to use this library for a Windows Phone 8.1 app, and ideally I'd like to define a `Windows.UI.Xaml.Controls.Canvas` (i.e. a `<Canvas />` element in my `.xaml` page) and draw onto that. Is that possible? How?

I can't seem to figure it out from the readme, and my google searches give too much noise for "graphics" when I try to search for stuff related to "ngraphics"...

Thanks for the help!

**Comment by Henkoglobin** [comment]
Have a look at [NControl](https://github.com/chrfalch/NControl), which uses an `System.Windows.Controls.Canvas` for drawing. Maybe that will help you
