### ISSUE TITLE
On iOS, Path.ArcTo() draws a straight line instead of an Arc

### ISSUE THREAD

**Issue by brianflahive** [praeclarum/NGraphics#30]

**Comment by BlueRaja** [comment]
Why did you close this?  Was it not actually a bug?

**Comment by brianflahive** [comment]
It was a bug on the version I downloaded with NControl, but seems to be okay when I download directly from https://github.com/praeclarum/NGraphics/.

**Comment by chrfalch** [comment]
Remember that NControl only references the released and pusbished NGraphics package on NuGet so updates to NGraphics that are not published will not be used when using NControl.
