### ISSUE TITLE
Drawing circles doesnt always work right

### ISSUE THREAD

**Issue by Clancey** [praeclarum/NGraphics#31]
![screenshot 2015-07-29 22 29 36](https://cloud.githubusercontent.com/assets/256046/8977027/79cd5622-3641-11e5-8040-8caf225628f6.png)

Here is a link to the SVG: https://www.dropbox.com/s/l9wazhnuiv35k9y/sliderThumb.svg?dl=0

**Comment by BlueRaja** [comment]
If you open the svg in notepad, you'll notice the "circle" is actually a `rect`.  My guess is that our SVG parser doesn't support [`fill-rule`](http://www.w3.org/TR/SVG/painting.html#FillRuleProperty).

I'm not actually a part of this project and have no incentive to fix this issue, but this should get you on the right track.  If you do add support for `fill-rule`, please submit a pull-request so others can benefit from your work in the future!

**Comment by praeclarum** [comment]
Yep, we're missing support for `rx`.

Would also seem that we're not stroking with a gradient.

I've added this test file and will work at it.

**Comment by praeclarum** [comment]
Fixed in c0e6f0414b065d5eba61602e4573b6127f1b6812
