### ISSUE TITLE
Support for WinRT?

### ISSUE THREAD

**Issue by thomaslevesque** [praeclarum/NGraphics#6]
This lib looks great, but it seems to be missing support for WinRT... System.Drawing is only available in the full desktop framework. Do you intend to support Windows Phone / Windows Store / Universal apps as well?

**Comment by praeclarum** [comment]
I do intend to and was hoping to wait for Microsoft to announce how Windows Unified is going to work.

**Comment by thomaslevesque** [comment]
I guess that makes sense; no point in doing the work twice...

**Comment by chrfalch** [comment]
Since Windows Phone 8/8.1 might be around for a while, maybe it would be interesting to investigate implementing these platforms?
