### ISSUE TITLE
Inconsistent default FillMode/FillType

### ISSUE THREAD

**Issue by RustyCZ** [praeclarum/NGraphics#81]
Android uses different default FillType in DrawPath compared to .Net implementation. It should be changed to Path.FillType.EVEN_ODD. I have attached SVG to test the behaviour. In Android it is currently drawn incorrectly with filled circle.
[B01.zip](https://github.com/praeclarum/NGraphics/files/868372/B01.zip)

**Comment by praeclarum** [comment]
Thank you, I'll look into it!
